/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0A2540',
        accent: '#0066CC',
        'accent-light': '#E8F1FB',
        'text-main': '#1A1F36',
        'text-muted': '#5A6478',
        'bg-soft': '#F7F9FC',
        border: '#E3E8EF',
        success: '#00875A',
        // New app design system tokens (authenticated pages)
        app: {
          primary: '#0B2A4A',
          accent: '#4FC3F7',
          bg: '#F4F7FA',
          text: '#1E2A3A',
          muted: '#7A8A9A',
          'sidebar-link': '#B0C4DE',
          border: '#E8EDF4',
        },
        // Status badge colors (app pages)
        'status-in-progress-bg': '#E3F0FF',
        'status-in-progress-text': '#1A6BB0',
        'status-completed-bg': '#E0F7E9',
        'status-completed-text': '#1A8A4A',
        'status-pending-bg': '#FFF3E0',
        'status-pending-text': '#B06A1A',
        'status-review-bg': '#FCE4EC',
        'status-review-text': '#B01A3A',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'sans-serif'],
      },
      boxShadow: {
        'sm': '0 1px 3px rgba(10, 37, 64, 0.06)',
        'md': '0 4px 12px rgba(10, 37, 64, 0.08)',
      },
      keyframes: {
        'toast-in-left':   { '0%': { transform: 'translateX(-110%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        'toast-out-left':  { '0%': { transform: 'translateX(0)', opacity: '1' },     '100%': { transform: 'translateX(-110%)', opacity: '0' } },
        'toast-in-right':  { '0%': { transform: 'translateX(110%)', opacity: '0' },  '100%': { transform: 'translateX(0)', opacity: '1' } },
        'toast-out-right': { '0%': { transform: 'translateX(0)', opacity: '1' },      '100%': { transform: 'translateX(110%)', opacity: '0' } },
        'toast-in-down':   { '0%': { transform: 'translateY(-110%)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        'toast-out-down':  { '0%': { transform: 'translateY(0)', opacity: '1' },      '100%': { transform: 'translateY(-110%)', opacity: '0' } },
        'toast-in-up':     { '0%': { transform: 'translateY(110%)', opacity: '0' },  '100%': { transform: 'translateY(0)', opacity: '1' } },
        'toast-out-up':    { '0%': { transform: 'translateY(0)', opacity: '1' },      '100%': { transform: 'translateY(110%)', opacity: '0' } },
        'slide-in-right':  { '0%': { transform: 'translateX(100%)', opacity: '0' },  '100%': { transform: 'translateX(0)', opacity: '1' } },
        'slide-out-left':  { '0%': { transform: 'translateX(0)', opacity: '1' },     '100%': { transform: 'translateX(-100%)', opacity: '0' } },
        'slide-in-left':   { '0%': { transform: 'translateX(-100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        'slide-out-right': { '0%': { transform: 'translateX(0)', opacity: '1' },      '100%': { transform: 'translateX(100%)', opacity: '0' } },
      },
      animation: {
        'toast-in-left':   'toast-in-left 250ms cubic-bezier(0.22,1,0.36,1)',
        'toast-out-left':  'toast-out-left 200ms ease-in forwards',
        'toast-in-right':  'toast-in-right 250ms cubic-bezier(0.22,1,0.36,1)',
        'toast-out-right': 'toast-out-right 200ms ease-in forwards',
        'toast-in-down':   'toast-in-down 250ms cubic-bezier(0.22,1,0.36,1)',
        'toast-out-down':  'toast-out-down 200ms ease-in forwards',
        'toast-in-up':     'toast-in-up 250ms cubic-bezier(0.22,1,0.36,1)',
        'toast-out-up':    'toast-out-up 200ms ease-in forwards',
        'slide-in-right':  'slide-in-right 300ms cubic-bezier(0.22,1,0.36,1)',
        'slide-out-left':  'slide-out-left 300ms cubic-bezier(0.22,1,0.36,1) forwards',
        'slide-in-left':   'slide-in-left 300ms cubic-bezier(0.22,1,0.36,1)',
        'slide-out-right': 'slide-out-right 300ms cubic-bezier(0.22,1,0.36,1) forwards',
      },
    },
  },
  plugins: [],
}