/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0A2540',
        accent: '#0066CC',
        'accent-light': '#E8F1FB',
        'text-main': '#1A1F36',
        'text-muted': '#5A6478',
        'bg-soft': '#F7F9FC',
        border: '#E3E8EF',
        success: '#00875A',
        // App design system tokens (authenticated pages)
        app: {
          primary: '#0B2A4A',
          accent: '#0066CC',
          bg: '#F4F7FC',
          text: '#1E293B',
          muted: '#5E6F8D',
          'sidebar-link': '#B0C4DE',
          border: '#EEF2F8',
          'border-hover': '#CBD9E8',
          'surface-alt': '#F8FAFF',
        },
        // Stat icon colors
        'stat-total': '#0066CC',
        'stat-progreso': '#F59E0B',
        'stat-completado': '#10B981',
        'stat-revision': '#F97316',
        // Status badge colors (plan palette)
        'status-in-progress-bg': '#DBEAFE',
        'status-in-progress-text': '#1D4ED8',
        'status-completed-bg': '#D1FAE5',
        'status-completed-text': '#065F46',
        'status-pending-bg': '#FEF3C7',
        'status-pending-text': '#B45309',
        'status-review-bg': '#FED7AA',
        'status-review-text': '#9A3412',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'sans-serif'],
      },
      boxShadow: {
        'sm': '0 1px 3px rgba(10, 37, 64, 0.06)',
        'md': '0 4px 12px rgba(10, 37, 64, 0.08)',
      },
      keyframes: {
        'toast-in-left':   { '0%': { transform: 'translateX(-110%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        'toast-out-left':  { '0%': { transform: 'translateX(0)', opacity: '1' },     '100%': { transform: 'translateX(-110%)', opacity: '0' } },
        'toast-in-right':  { '0%': { transform: 'translateX(110%)', opacity: '0' },  '100%': { transform: 'translateX(0)', opacity: '1' } },
        'toast-out-right': { '0%': { transform: 'translateX(0)', opacity: '1' },      '100%': { transform: 'translateX(110%)', opacity: '0' } },
        'toast-in-down':   { '0%': { transform: 'translateY(-110%)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        'toast-out-down':  { '0%': { transform: 'translateY(0)', opacity: '1' },      '100%': { transform: 'translateY(-110%)', opacity: '0' } },
        'toast-in-up':     { '0%': { transform: 'translateY(110%)', opacity: '0' },  '100%': { transform: 'translateY(0)', opacity: '1' } },
        'toast-out-up':    { '0%': { transform: 'translateY(0)', opacity: '1' },      '100%': { transform: 'translateY(110%)', opacity: '0' } },
        'slide-in-right':  { '0%': { transform: 'translateX(100%)', opacity: '0' },  '100%': { transform: 'translateX(0)', opacity: '1' } },
        'slide-out-left':  { '0%': { transform: 'translateX(0)', opacity: '1' },     '100%': { transform: 'translateX(-100%)', opacity: '0' } },
        'slide-in-left':   { '0%': { transform: 'translateX(-100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        'slide-out-right': { '0%': { transform: 'translateX(0)', opacity: '1' },      '100%': { transform: 'translateX(100%)', opacity: '0' } },
      },
      animation: {
        'toast-in-left':   'toast-in-left 250ms cubic-bezier(0.22,1,0.36,1)',
        'toast-out-left':  'toast-out-left 200ms ease-in forwards',
        'toast-in-right':  'toast-in-right 250ms cubic-bezier(0.22,1,0.36,1)',
        'toast-out-right': 'toast-out-right 200ms ease-in forwards',
        'toast-in-down':   'toast-in-down 250ms cubic-bezier(0.22,1,0.36,1)',
        'toast-out-down':  'toast-out-down 200ms ease-in forwards',
        'toast-in-up':     'toast-in-up 250ms cubic-bezier(0.22,1,0.36,1)',
        'toast-out-up':    'toast-out-up 200ms ease-in forwards',
        'slide-in-right':  'slide-in-right 300ms cubic-bezier(0.22,1,0.36,1)',
        'slide-out-left':  'slide-out-left 300ms cubic-bezier(0.22,1,0.36,1) forwards',
        'slide-in-left':   'slide-in-left 300ms cubic-bezier(0.22,1,0.36,1)',
        'slide-out-right': 'slide-out-right 300ms cubic-bezier(0.22,1,0.36,1) forwards',
      },
    },
  },
  plugins: [],
}