"""baseline

Revision ID: 4e12a2883ac9
Revises: 
Create Date: 2026-07-17 17:10:12.214710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e12a2883ac9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_company_user_id'), 'company', ['user_id'], unique=False)
    op.create_table('consultant',
    sa.Column('consultant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('certifications', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.PrimaryKeyConstraint('consultant_id')
    )
    op.create_index(op.f('ix_consultant_user_id'), 'consultant', ['user_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('answers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('free_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_process_id'), 'findings', ['process_id'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('summary_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_process_id'), 'plans', ['process_id'], unique=True)
    op.create_table('processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consultant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('pre_diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iso_standard', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_company_id'), 'processes', ['company_id'], unique=False)
    op.create_index(op.f('ix_processes_consultant_id'), 'processes', ['consultant_id'], unique=False)
    op.create_index(op.f('ix_processes_iso_standard'), 'processes', ['iso_standard'], unique=False)
    op.create_index(op.f('ix_processes_status'), 'processes', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('estimated_effort', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('owner_role', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_plan_id'), 'tasks', ['plan_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gov_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_plan_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_processes_status'), table_name='processes')
    op.drop_index(op.f('ix_processes_iso_standard'), table_name='processes')
    op.drop_index(op.f('ix_processes_consultant_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_company_id'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_plans_process_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_findings_process_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_consultant_user_id'), table_name='consultant')
    op.drop_table('consultant')
    op.drop_index(op.f('ix_company_user_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
